### ISSUE TITLE
Doesn't use global layout

### ISSUE THREAD

**Issue by oleksify** [citrus/spree_essential_cms#1]
Why pages doesn't use global site layout?

**Comment by citrus** [comment]
The pages controller inherits from the ApplicationController rather than Spree::BaseController. Just make your application controller inherit from the Spree::BaseController and you should be good to go...

```
class ApplicationController < Spree::BaseController
    protect_from_forgery
end
```

Check out https://github.com/citrus/spree_essentials_demo for a complete example..

**Comment by oleksify** [comment]
Working, thanks!

**Comment by citrus** [comment]
No problemo! Let me know if you have any other questions...
