### ISSUE TITLE
Generator fails - cannot load such file -- generators/essentials_base

### ISSUE THREAD

**Issue by ghost** [citrus/spree_essential_cms#11]
``` ruby
bundle exec rails g spree_essentials:cms                                                                                                                                                           !900
[DEPRECATION WARNING] Nested I18n namespace lookup under "activerecord.attributes.spree/order" is no longer supported
/Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `require': cannot load such file -- generators/essentials_base (LoadError)
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `block in require'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `require'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/spree_essential_cms-0.3.0.rc1/lib/generators/spree_essentials/cms_generator.rb:1:in `<top (required)>'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `require'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `block in require'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `require'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/railties-3.1.4/lib/rails/generators.rb:297:in `block (2 levels) in lookup'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/railties-3.1.4/lib/rails/generators.rb:293:in `each'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/railties-3.1.4/lib/rails/generators.rb:293:in `block in lookup'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/railties-3.1.4/lib/rails/generators.rb:292:in `each'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/railties-3.1.4/lib/rails/generators.rb:292:in `lookup'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/railties-3.1.4/lib/rails/generators.rb:149:in `find_by_namespace'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/railties-3.1.4/lib/rails/generators.rb:166:in `invoke'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/railties-3.1.4/lib/rails/commands/generate.rb:12:in `<top (required)>'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `require'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `block in require'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `require'
    from /Users/dheerajkumar/.rvm/gems/ruby-1.9.3-p0@sample/gems/railties-3.1.4/lib/rails/commands.rb:28:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by citrus** [comment]
I've removed `generators/essentials_base` from spree essentials in v0.4.0.rc3. The CMS has been updated on [master](https://github.com/citrus/spree_essential_cms/commit/fc2604339a21888693a0fde20e241943257e7a23) and I'll be releasing a new stable version hopefully today.

Let me know if that works!

-Spencer

**Comment by dp6ai** [comment]
Hi,

I've got the same issue.

Any sign of a fix for this?

thanks

**Comment by citrus** [comment]
The fix is using spree_essential_cms from the master branch vs the last stable release.

In your gemfile:

``` ruby
gem 'spree_essential_cms', :git => 'git://github.com/citrus/spree_essential_cms.git'
```

Then run `bundle update spree_essential_cms`

Let me know if that works...

**Comment by dp6ai** [comment]
Sorted.  

Thanks

**Comment by dp6ai** [comment]
Spoke to soon...

Completed 500 Internal Server Error in 121ms

ActionView::Template::Error (undefined method `images' for nil:NilClass):
    1: <% unless @page.images.empty? %>
    2:   <%= render 'spree/shared/slideshow', :images => @page.images, :size => :slide %>
    3: <% end %>
    4: 

sorry

**Comment by citrus** [comment]
@dp6ai that's a different error. You're asking `@page` for it's images, but `@page` is nil. You'll need to give me more info to diagnose further.

**Comment by dp6ai** [comment]
Installed the gem as per instructions and then refreshed my home page.

---

activesupport (3.1.3) lib/active_support/whiny_nil.rb:48:in `method_missing'
/Users/name/.rvm/gems/ruby-1.9.3-p0/bundler/gems/spree_essential_cms-189093ab69f0/app/views/spree/pages/home.html.erb:1:in`___sers_name__rvm_gems_ruby_______p__bundler_gems_spree_essential_cms_______ab__f__app_views_spree_pages_home_html_erb___1297530671091168626_70155355656460'
actionpack (3.1.3) lib/action_view/template.rb:171:in `block in render'
activesupport (3.1.3) lib/active_support/notifications.rb:55:in`instrument'
actionpack (3.1.3) lib/action_view/template.rb:169:in `render'
actionpack (3.1.3) lib/action_view/renderer/template_renderer.rb:40:in`block (2 levels) in render_template'
actionpack (3.1.3) lib/action_view/renderer/abstract_renderer.rb:33:in `block in instrument'
activesupport (3.1.3) lib/active_support/notifications.rb:53:in`block in instrument'
activesupport (3.1.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.1.3) lib/active_support/notifications.rb:53:in`instrument'
actionpack (3.1.3) lib/action_view/renderer/abstract_renderer.rb:33:in `instrument'
actionpack (3.1.3) lib/action_view/renderer/template_renderer.rb:39:in`block in render_template'
actionpack (3.1.3) lib/action_view/renderer/template_renderer.rb:47:in `render_with_layout'
actionpack (3.1.3) lib/action_view/renderer/template_renderer.rb:38:in`render_template'
actionpack (3.1.3) lib/action_view/renderer/template_renderer.rb:12:in `block in render'
actionpack (3.1.3) lib/action_view/renderer/abstract_renderer.rb:22:in`wrap_formats'
actionpack (3.1.3) lib/action_view/renderer/template_renderer.rb:9:in `render'
actionpack (3.1.3) lib/action_view/renderer/renderer.rb:36:in`render_template'
actionpack (3.1.3) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.1.3) lib/abstract_controller/rendering.rb:120:in`_render_template'
actionpack (3.1.3) lib/action_controller/metal/streaming.rb:250:in `_render_template'
actionpack (3.1.3) lib/abstract_controller/rendering.rb:114:in`render_to_body'
actionpack (3.1.3) lib/action_controller/metal/renderers.rb:30:in `render_to_body'
actionpack (3.1.3) lib/action_controller/metal/compatibility.rb:43:in`render_to_body'
actionpack (3.1.3) lib/abstract_controller/rendering.rb:99:in `render'
actionpack (3.1.3) lib/action_controller/metal/rendering.rb:16:in`render'
actionpack (3.1.3) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.1.3) lib/active_support/core_ext/benchmark.rb:5:in`block in ms'
/Users/name/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
activesupport (3.1.3) lib/active_support/core_ext/benchmark.rb:5:in`ms'
actionpack (3.1.3) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.1.3) lib/action_controller/metal/instrumentation.rb:78:in`cleanup_view_runtime'
activerecord (3.1.3) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.1.3) lib/action_controller/metal/instrumentation.rb:39:in`render'
/Users/name/.rvm/gems/ruby-1.9.3-p0/bundler/gems/spree_essential_cms-189093ab69f0/app/controllers/spree/home_controller_decorator.rb:8:in `index'
actionpack (3.1.3) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.1.3) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.1.3) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (3.1.3) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.1.3) lib/active_support/callbacks.rb:479:in`_run__4371613223662020123__process_action__328366494556203249__callbacks'
activesupport (3.1.3) lib/active_support/callbacks.rb:386:in `_run_process_action_callbacks'
activesupport (3.1.3) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.1.3) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.1.3) lib/action_controller/metal/rescue.rb:17:in`process_action'
actionpack (3.1.3) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.1.3) lib/active_support/notifications.rb:53:in`block in instrument'
activesupport (3.1.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.1.3) lib/active_support/notifications.rb:53:in`instrument'
actionpack (3.1.3) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.1.3) lib/action_controller/metal/params_wrapper.rb:201:in`process_action'
activerecord (3.1.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.1.3) lib/abstract_controller/base.rb:121:in`process'
actionpack (3.1.3) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.1.3) lib/action_controller/metal.rb:193:in`dispatch'
actionpack (3.1.3) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.1.3) lib/action_controller/metal.rb:236:in`block in action'
actionpack (3.1.3) lib/action_dispatch/routing/route_set.rb:65:in `call'
actionpack (3.1.3) lib/action_dispatch/routing/route_set.rb:65:in`dispatch'
actionpack (3.1.3) lib/action_dispatch/routing/route_set.rb:29:in `call'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in`block in call'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `block in recognize'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:68:in`optimized_each'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in`call'
actionpack (3.1.3) lib/action_dispatch/routing/route_set.rb:532:in `call'
spree_core (1.0.0) lib/spree/core/middleware/redirect_legacy_product_url.rb:13:in`call'
spree_core (1.0.0) lib/spree/core/middleware/seo_assist.rb:27:in `call'
railties (3.1.3) lib/rails/engine.rb:456:in`call'
railties (3.1.3) lib/rails/railtie/configurable.rb:30:in `method_missing'
rack-mount (0.8.3) lib/rack/mount/prefix.rb:26:in`call'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in `block in call'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in`block in recognize'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:75:in `optimized_each'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in`recognize'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in `call'
actionpack (3.1.3) lib/action_dispatch/routing/route_set.rb:532:in`call'
warden (1.0.6) lib/warden/manager.rb:35:in `block in call'
warden (1.0.6) lib/warden/manager.rb:34:in`catch'
warden (1.0.6) lib/warden/manager.rb:34:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
rack (1.3.6) lib/rack/etag.rb:23:in `call'
rack (1.3.6) lib/rack/conditionalget.rb:25:in`call'
actionpack (3.1.3) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
actionpack (3.1.3) lib/action_dispatch/middleware/flash.rb:247:in `call'
rack (1.3.6) lib/rack/session/abstract/id.rb:195:in`context'
rack (1.3.6) lib/rack/session/abstract/id.rb:190:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/cookies.rb:331:in`call'
activerecord (3.1.3) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.1.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:477:in`call'
actionpack (3.1.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (3.1.3) lib/active_support/callbacks.rb:392:in`_run_call_callbacks'
activesupport (3.1.3) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.1.3) lib/action_dispatch/middleware/callbacks.rb:28:in`call'
actionpack (3.1.3) lib/action_dispatch/middleware/reloader.rb:68:in `call'
rack (1.3.6) lib/rack/sendfile.rb:101:in`call'
actionpack (3.1.3) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/show_exceptions.rb:47:in`call'
railties (3.1.3) lib/rails/rack/logger.rb:13:in `call'
rack (1.3.6) lib/rack/methodoverride.rb:24:in`call'
rack (1.3.6) lib/rack/runtime.rb:17:in `call'
activesupport (3.1.3) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
rack (1.3.6) lib/rack/lock.rb:15:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/static.rb:53:in`call'
railties (3.1.3) lib/rails/engine.rb:456:in `call'
rack (1.3.6) lib/rack/content_length.rb:14:in`call'
railties (3.1.3) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.3.6) lib/rack/handler/webrick.rb:59:in`service'
/Users/name/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/Users/name/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'
/Users/name/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

---

**Comment by citrus** [comment]
Do you have a homepage (path "/") in the database?

**Comment by dp6ai** [comment]
i think my database is fairly standard.

I dont remember setting the homepage at any point. 

Where would i do that?

**Comment by citrus** [comment]
Log in to the admin then go to Content > Pages > New

The just make sure you set the path = /

dp6ai wrote:

**Comment by citrus** [comment]
@dp6ai I just pushed b0fa128 which will redirect you to /products if no homepage exists.

Run `bundle update spree_essential_cms` to get the patch

**Comment by ghost** [comment]
Issue solved, thanks!

**Comment by citrus** [comment]
Right on :) :beer: :beer:

**Comment by dp6ai** [comment]
All working.

thanks
