### ISSUE TITLE
markItUp image browser

### ISSUE THREAD

**Issue by sbounmy** [citrus/spree_essential_cms#15]
Hi @citrus,

When I am creating a page, I want to be able to control images' positions.

There is an 'image browser' function in the markItUp JQuery  plugin which is not implemented, what do you think ?

Thanks!

**Comment by citrus** [comment]
Do it!! Sounds like it could be handy :)

Any way we could make it work with the custom image picker too?

**Comment by sbounmy** [comment]
Hum I might be missing something, what is the custom image picker ?
Do we have an existing way to control content's images position ?

**Comment by citrus** [comment]
The custom image allows you to add images to your content that you've added the the 'uploads' section of the admin... Similar to that of Refinery CMS.

It's the second button from the right, next to the 'Preview' button.. 

To be honest it needs a bit of work.. Currently there is no pagination when listing the uploads in the picker, and the UI is a bit confusing...

**Comment by citrus** [comment]
Oh and sorry to answer your question there is no code in place to choose how an image is positioned..

**Comment by sbounmy** [comment]
doh, I just saw the uploads section, its working great with the image browser !
I can partially control how images are displayed now within markItUp, thanks !
To fully control images' position I wil have to play with img class & css i guess.

Thanks for your help @citrus !

**Comment by citrus** [comment]
Haha right on, good luck! Remember too that you can also put regular HTML into the markitup editor.. This way you can use Spree's css column framework to really customize your pages :)   :beer: :beer:

maybe we should be adding some of this to the docs ;)
