### ISSUE TITLE
redirect_to products_url ?

### ISSUE THREAD

**Issue by lafeber** [citrus/spree_essential_cms#16]
This plugin redirects root to products_url if there's no page with path '/'

I had to place   

```
skip_before_filter :get_homepage 
```

in my own home_controller_decorator.rb to fix it.

**Comment by citrus** [comment]
Thanks for pointing this out. I'll remove the redirect next time I get a chance to work on this ;)

**Comment by lafeber** [comment]
Ok, thanks!

**Comment by citrus** [comment]
This is fixed on the master banch.
