### ISSUE TITLE
meta_search and Ransack

### ISSUE THREAD

**Issue by ethier** [citrus/spree_essential_cms#17]
I'm new to Rails/spree, so apologies for the poor explanation. Trying to puzzle this out.

It looks like the sort_link arguments in index.html.erb need to either be updated, or something else done with the meta_search support.

A week ago, this [issue](https://github.com/ernie/ransack/issues/84) in Ransack was addressed by adding the ability to use named routes in `sort_link` via:

`sort_link [:engine, @search]`

Sadly, this still results in:

`First argument must be a Ransack::Search!`

When using the Contents tab in Spree admin (on 1.1.0.beta). Also, I had to add the metasearch gem to the application Gemfile to get to this point as well.

I've tried with the following:

```
<th><%= sort_link [:spree, @search], :title, t("page.title") %></th>
<th><%= sort_link [:spree, @search], :path, t("page.path") %></th>
<th><%= sort_link [:spree, @search], :accessible, t("page.accessible") %></th>
<th><%= sort_link [:spree, @search], :visible, t("page.visible") %></th>
```

But, it still throws the Ransack error mentioned above.

To be honest, it looks like the spree team has replaced metasearch with Ransack so parts of this extension may need to be re-written.

**Comment by ethier** [comment]
Closed in favour of 19.

**Comment by 4ydin** [comment]
i got same problem with you. how did you solve the problem? @ethier
