### ISSUE TITLE
/Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `require': cannot load such file -- generators/essentials_base (LoadError)

### ISSUE THREAD

**Issue by halcasteel** [citrus/spree_essential_cms#19]
bundle exec rails g spree_essentials:cms

[DEPRECATION] `insert_after` hook method is deprecated, replace hook call with: 
Deface::Override.new(:virtual_path => "admin/configurations/index",
                     :name => "converted_admin_configurations_menu_674664951",
                     :insert_after => "[data-hook='admin_configurations_menu'], #admin_configurations_menu[data-hook]",
                     :text => "<%= configurations_menu_item(I18n.t('captcha.captcha_settings'), admin_captcha_settings_path, I18n.t('captcha.manage_keys')) %>",
                     :disabled => false)

[WARNING] You no longer need to manually require overrides, remove require for 'converted_admin_configurations_menu_674664951'.
[DEPRECATION] `insert_after` hook method is deprecated, replace hook call with: 
Deface::Override.new(:virtual_path => "products/show",
                     :name => "converted_product_description_455609648",
                     :insert_after => "[data-hook='product_description'], #product_description[data-hook]",
                     :text => "<p class=\"email_to_friend\">
        <%= link_to(t('email_to_friend.send_to_friend'), email_to_friend_url('product', @product)) %>
    </p>",
                     :disabled => false)

[WARNING] You no longer need to manually require overrides, remove require for 'converted_product_description_455609648'.
[DEPRECATION WARNING] Nested I18n namespace lookup under "activerecord.attributes.spree/order" is no longer supported
/Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `require': cannot load such file -- generators/essentials_base (LoadError)
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in`block in require'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640:in`new_constants_in'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in`require'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/spree_essential_cms-0.3.0.rc1/lib/generators/spree_essentials/cms_generator.rb:1:in `<top (required)>'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in`require'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `block in require'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in`block in load_dependency'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in`load_dependency'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `require'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/railties-3.1.4/lib/rails/generators.rb:297:in`block (2 levels) in lookup'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/railties-3.1.4/lib/rails/generators.rb:293:in `each'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/railties-3.1.4/lib/rails/generators.rb:293:in`block in lookup'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/railties-3.1.4/lib/rails/generators.rb:292:in `each'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/railties-3.1.4/lib/rails/generators.rb:292:in`lookup'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/railties-3.1.4/lib/rails/generators.rb:149:in `find_by_namespace'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/railties-3.1.4/lib/rails/generators.rb:166:in`invoke'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/railties-3.1.4/lib/rails/commands/generate.rb:12:in `<top (required)>'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in`require'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `block in require'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in`block in load_dependency'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223:in`load_dependency'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240:in `require'
    from /Users/halcasteel/.rvm/gems/ruby-1.9.3-head/gems/railties-3.1.4/lib/rails/commands.rb:28:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by citrus** [comment]
This could quite possibly be the worst issue report I've seen on my projects. Please be more specific and use markdown to make your report legible. 

I'll put in some effort once you do as well ;)

:beer:

**Comment by halcasteel** [comment]
Sorry it was so illegible. Next time I will do better.

**Comment by citrus** [comment]
Thanks!!
