### ISSUE TITLE
active_merchant dependancy

### ISSUE THREAD

**Issue by wejrowski** [citrus/spree_essential_cms#2]
I'm trying to install the spree_active_shipping gem. I'm getting an error that the gem conflicts with your gem dependancies.. and I'm not sure how to resolve it. I was looking into why/where your spree_essential_cms is using activemerchant and I couldn't find that either.

```
Bundler could not find compatible versions for gem "activemerchant":
  In Gemfile:
    spree_essential_cms depends on
      activemerchant (= 1.14.0)

    spree_active_shipping depends on
      activemerchant (1.9.0)
```

**Comment by citrus** [comment]
I'm not sure why this is happening... Spree_essential_cms doesn't rely on activemerchant directly. Which version of spree & spree_essentials are you running?

**Comment by wejrowski** [comment]
Just using the 'spree' gem. So whichever that is (I have 0.60.1 and  0.40.0 installed). And spree_essentials 0.2.2.

Weird it's showing that eror your gem doesn't use it. Is there a way to find out exactly where that dependency is coming from?

Thanks for the help!

**Comment by citrus** [comment]
I would recommend adding a version constraint to the spree gem in your Gemfile:

```
gem 'spree', '~> 0.60.1'
```

Both spree [0.40.0](https://rubygems.org/gems/spree_core/versions/0.40.0) and [0.60.1](https://rubygems.org/gems/spree_core/versions/0.60.1) require activemerchant = 1.15.0, and [spree_active_shipping](https://rubygems.org/gems/spree_active_shipping/versions/1.0.0) requires activemerchant = 1.9.0.

So I'm not sure that this is related to spree_essential_cms. Maybe you could take it out of your Gemfile for debugging? Also, pasting your Gemfile might shed some more light...

**Comment by wejrowski** [comment]
Hmm, so now it's saying it's an issue between spree and spree_active_shipping. Thanks. I suppose I'll ask those guys, unless you have any solutions off hand.

```
Bundler could not find compatible versions for gem "activemerchant":
  In Gemfile:
spree (~> 0.60.1) depends on
  activemerchant (= 1.15.0)

spree_active_shipping depends on
  activemerchant (1.9.0)
```

**Comment by citrus** [comment]
It looks like v1.0.0 of spree_active_shipping is the culprit here... The [released version](https://rubygems.org/gems/spree_active_shipping) depends on activemerchant but the [edge version](https://github.com/spree/spree_active_shipping/blob/master/spree_active_shipping.gemspec) doesn't. So in your Gemfile just change your spree_active_shipping line to:

```
gem 'spree_active_merchant', :git => 'git://github.com/spree/spree_active_shipping.git'
```

I'd bring this up with the spree folks too so future users don't have the same issues...

Hope that helps!

-Spencer

**Comment by wejrowski** [comment]
Genius. Ah thanks! BTW I think you meant to say

```
gem 'spree_active_shipping', :git => 'git://github.com/spree/spree_active_shipping.git'
```

Random question. When you use gems with git, where do these install to? They never appear in the gems directory.

**Comment by wejrowski** [comment]
Answered my question with

```
bundle show spree_active_shipping
```

**Comment by citrus** [comment]
haha yes, definitely meant 'spree_active_shipping' hahaha...

And right on for finding `bundle show`!

**Comment by jclay** [comment]
Thanks for this! Pulling from the git repo fixed it for me also.
