### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by sbounmy** [citrus/spree_essential_cms#20]
Hi @citrus !

I'm looking to implement multi language support to essential cms !
I've recently working on https://github.com/jipiboily/spree_multi_lingual.git, it would be nice to depend on this gem and bring the necessary changes to spree_essential_cms to support multi language.

WDYT ?
Stephane.

**Comment by citrus** [comment]
That would be awesome!! I'm all for it!

-Spencer

**Comment by sbounmy** [comment]
I gonna work on that, stay tuned :)

**Comment by sbounmy** [comment]
a lot of tests are failling, do you know whats wrong ? :/

**Comment by citrus** [comment]
Spree 1.0.3 or 1.1.0?

**Comment by sbounmy** [comment]
1.0.3, I have the same errors as travis

**Comment by citrus** [comment]
Try v1.0.2 or v1.0.1..

I opened [this issue](https://github.com/spree/spree/issues/1292) after the tests started failing on travis which resulted in [this PR](https://github.com/spree/spree/pull/1296) to ensure this sort of thing doesn't happen any more.

Hope that helps!

-Spencer

**Comment by sbounmy** [comment]
Hey @citrus I tried with 1.0.1 looks like I have the same failures, I will try to investigate further this evening.
Thanks!

**Comment by citrus** [comment]
I just ran the tests against 1.0.1 on my machine and got all green... 
Did you run `bundle exec dummier` to rebuild the test/dummy app?

-Spencer

Bounmy Stéphane wrote:

**Comment by sbounmy** [comment]
Thanks @citrus! I have only one failure left now :)

**Comment by citrus** [comment]
Which is it? I'm getting one failure on Travis too but am not seeing it locally.. Any idea? 

-Spencer

via iPhone 4S

**Comment by sbounmy** [comment]
fixed in #21

**Comment by citrus** [comment]
we can close this, right?

Thanks again Stephane!

**Comment by sbounmy** [comment]
yes we can close !

btw can you please create a 1-0-stable branch for people who are still using spree 1.0.x ? I've got one here https://github.com/sbounmy/spree_essential_cms/tree/1-0-stable I will probably implement i18n features against 1.0.x first.

Thanks !

**Comment by citrus** [comment]
Hey Stephane,

I just pushed a 1.0.x branch.. not sure why I hadn't done that sooner!

Cheers,

-Spencer
