### ISSUE TITLE
undefined markdownSettings

### ISSUE THREAD

**Issue by sbounmy** [citrus/spree_essential_cms#22]
Hi @citrus,

looks like master and 1-0-stable js is broken in contents/_form.html.erb: 

``` javascript
 $('#content_body').markItUp(markdownSettings);
//ReferenceError: markdownSettings is not defined
```

I can't find where markdownSettings is defined in the code. :/

**Comment by sbounmy** [comment]
ups I was missing require admin/spree_essentials in my admin/all.js.

I noticed in spree_essentials/engine : 

``` ruby
    initializer :assets do |config| 
      Rails.application.config.assets.precompile += %w( admin/markitup.css admin/date.js admin/jquery.autodate.js admin/jquery.markitup.js admin/markdown.set.js )
    end
```

Maybe we can remove it since we require them using sprockets

**Comment by citrus** [comment]
Right on :) What do you mean 'remove them'?

**Comment by sbounmy** [comment]
I meant since we have in admin/spree_essentials.js / .css :

``` javascript
//= require_tree .
```

We don't necessarily need to precompile them in the initializer.

I mean it's working so far for my extensions.

**Comment by citrus** [comment]
Oh gotcha! Ya we can go ahead and remove the precompile list since it's not needed. Thanks!
