### ISSUE TITLE
Sortable tables not saving

### ISSUE THREAD

**Issue by dvictory** [citrus/spree_essential_cms#23]
The sortable tables in pages/index, contents/index and _content do not use the proper dom_id for the ajax to work.  When you try and rearrange then table rows you get a 500 server error.

In all the files the <tr id=<%= dom_id%>  should be changed to <%= spree_dom_id %>

I would do a pull request, but I kinda suck at git right now and I am afraid I will screw it up.

Thanks, Derek

**Comment by citrus** [comment]
I'll take a look. Thanks for the report!

**Comment by dvictory** [comment]
It is really hard to write test scripts to test drag and drop with sortable list, but that is the issue.

here is the commit that broke it - 
https://github.com/spree/spree/commit/ad08b7634e042401221709b21a8db810b1bb86fa

**Comment by citrus** [comment]
It is tricky to write drag and drop tests. I've tried a few times but haven't found a solution that works well. 

Anyways I just pushed a fix for this issue...  (5c265c702f2d9c819c754051459cdf6b679f772f)

Cheers!

-Spencer
