### ISSUE TITLE
Rich text editor not displaying in Chrome

### ISSUE THREAD

**Issue by Limb** [citrus/spree_essential_cms#24]
The rich text editor does not load 95% in chrome on my mac. It show's up in safari fine however.

**Comment by citrus** [comment]
Did you figure this out?

**Comment by Limb** [comment]
Yes, turns out I was having conflicting cache issues between the test app
in the gem and my own app.
On May 15, 2012 1:23 PM, "Spencer Steffen" <
reply@reply.github.com>
wrote:
