### ISSUE TITLE
normalize attachment path

### ISSUE THREAD

**Issue by sbounmy** [citrus/spree_essential_cms#7]
Hi citrus,

I noticed spree_core is storing assets into public/spree/products/.
Would it be a good idea to follow the same convention and have the pages contents assets to be stored in spree/public/pages ?

Basically, the main point is having a single folder public/spree for all attachments which would ease deployment like capistrano :

``` ruby
run "ln -nfs #{shared_path}/spree #{release_path}/public/spree"
```

Stephane

**Comment by citrus** [comment]
I think this is a good idea :) Can you send me a pull request?

Thanks! :beer:
